name: Test
on:
  pull_request:
    branches:
      - main
jobs:
  build_web:
    name: Build web
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Decrypt archive
        env:
          PASSPHRASE: ${{ secrets.PASSPHRASE }}
        run: |
          gpg --quiet --batch --yes --decrypt --passphrase "$PASSPHRASE" --output "./archive.tar" "./archive.tar.gpg"
          tar -xf "./archive.tar"
          rm "./archive.tar"
      - name: Setup Flutter
        uses: tnc1997/github-actions/actions/setup-flutter@setup-flutter_v1
        with:
          channel: beta
      - name: Build web
        run: flutter build web --web-renderer "html"
      - name: Deploy hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_TIDAL_RUN_307407 }}
          projectId: tidal-run-307407
          repoToken: ${{ secrets.GITHUB_TOKEN }}
